### ISSUE TITLE
How does the SDP work for multiparty ?

### ISSUE THREAD

**Issue by sashasami03** [peterwittek/multipartite_entanglement#1]
In the tripartite.py it runs SDP for bi-separable states , if I just want to check the quantum violations of bell inequalities for tripartite case such as violation of Mermin inequality how do I go about it. Is it just like the bipartite case ?

A = generate_measurements(A_configuration, 'A')
B = generate_measurements(B_configuration, 'B')
C = generate_measurements(C_configuration, 'C') 
monomial_substitutions = projective_measurement_constraints(A, B,C)
sdpRelaxation = SdpRelaxation(flatten([A, B,C]))

Or is in tripartite/multipartite case  the moment matrix generated in a different fashion ? I am sorry for trivial issues but I understand how SDP works for checking quantum violations of  bell inequalities for bipartite case, but can't understand the method for tripartite or higher party cases.

**Comment by peterwittek** [comment]
The case is identical to the bipartite case. What you have written above is correct. What remains to be done is the definition of the inequality with the operators you got from the `generate_measurements` calls. Keep in mind that [Ncpol2sdpa](http://peterwittek.github.io/ncpol2sdpa/) expects an objective function to be minimized, so if you are looking for the maximum violation, your objective function will be `-whatever_inequality`.

**Comment by sashasami03** [comment]
I tried finding the maximum value of GYNI ( guess your neighbour inequality ) in tripartite case ( every party with two measurement with each measurement having two outcomes )
 I_{GYNI} =   1/4 (  P(000|000) + P(110|011) + P(011|101) + P(101|110) )
I expected max{ I_{GYNI} }  to be 1/3 ( for quantum ) but came out to be 0.5 for Q_2 and Q_3.
I also tried checking Mermin game's maximum violation ( a + b + c mod 2 = x.y.z ) which I expected to be
1 but came out to be 7/8 for Q_1 , Q_2 and Q_3.  Are there any conditions on probabilities corresponding to various projector operators that have to be added in addition to the monomial substitutions that I am missing i?   


# finding max{ I_GYNI }
from ncpol2sdpa import *

level = 3 

A_configuration = [2, 2]
B_configuration = [2, 2]
C_configuration = [2, 2]


A = generate_measurements(A_configuration, 'A') 
B = generate_measurements(B_configuration, 'B')
C = generate_measurements(C_configuration, 'C') 


monomial_substitutions = projective_measurement_constraints(A, B,C)
sdpRelaxation = SdpRelaxation(flatten([A, B,C]))

objective = 0.25*(A[0][0]*B[0][0]*C[0][0] + A[0][0]*B[1][0]*C[1][0] - A[0][0]*C[1][0] + A[1][0] - A[1][0]*B[0][0] + A[1][0]*B[0][0]*C[1][0] - A[1][0]*B[1][0] + A[1][0]*B[1][0]*C[0][0] - A[1][0]*C[0][0] + B[0][0] - B[0][0]*C[1][0] - B[1][0]*C[1][0] + C[1][0]) 
objective = objective * -1

sdpRelaxation.get_relaxation(level, objective=objective,substitutions=monomial_substitutions)
primal_nc, dual_nc, x_mat_nc, y_mat_nc = solve_sdp(sdpRelaxation,solver="cvxopt")

print primal_nc

**Comment by peterwittek** [comment]
I strongly do not recommend doing this, but if your inequality is as complex as the ones you mention, you can try abandoning the Collins-Gisin picture for debugging purposes. This means you have to generate all projectors within a measurement, plus imposing an extra equality for each measurement to ensure that the projectors add up to the identity. All of this has a tremendous computational overhead in the resulting SDP. I tried this with I_{GNYI}, and at Q_2, I got 0.29128344477. It should be more than 1/3 because we are approximating Q from outside, but the equality constraints force building localizing matrices, and that reduces numerical accuracy. If we try this with an arbitrary precision solver, I believe we would get the accurate answer. So most likely something goes wrong in the way you reconstruct the desired probabilities from the marginals.

Working with the projectors is counterintuitive anyway and we long had this problem of not having a simple way of saying something like p(ab|xy) or p(abc|xyz). I started working on a helper class that does this translation.

**Comment by sashasami03** [comment]
I will surely try the method you mentioned. 
Could you tell why you don't recommend solving the SDP with one less projection operator for each measurement if I want to see violation of inequalities like Mermin. How does it lead to errors such as I_{GYNI} exceeding 1 ? Also in the I_{GYNI} case few probabilities were negative for example corresponding to the operator C[0][0]. Also why is the first diagonal element of moment matrix T which corresponds to Identity operator not fixed to 1 ?

As you said listing all projection operators will still give me precision issues , how could I tackle this problem ?

Sorry for asking too many doubts but I really want to code to see the violations for various tripartite case inequalities.

**Comment by peterwittek** [comment]
I just commented on your gist with the code for including all projection operators. The main reason against this method is the huge increase in the size of the SDP and the loss of accuracy.

So to be clear, I recommend the method included in the examples, that is, the Collins-Gisin picture: we leave out one projection operator for each measurement and we drop the add-up-to-identity constraints. This will give you the most precise result. I am hoping to finish the probability function I mentioned in a short while to overcome the difficulty of the syntax.

**Comment by peterwittek** [comment]
I just pushed the `Probability` class to the Ncpol2sdpa repository. The following code snippet gives  about 0.2913 with SDPA, Mosek, and Cvxopt:

```python
from __future__ import print_function
from ncpol2sdpa import SdpRelaxation, solve_sdp, Probability
P = Probability([2, 2], [2, 2], [2, 2])
sdpRelaxation = SdpRelaxation(P.get_all_operators(), verbose=1)

GYNI = 0.25*(P([0,0,0],[0,0,0]) + P([1,1,0],[0,1,1]) +
             P([0,1,1],[1,0,1]) + P([1,0,1],[1,1,0]))

sdpRelaxation.get_relaxation(2, objective=-GYNI,
                             substitutions=P.substitutions)
solve_sdp(sdpRelaxation, solver="cvxopt")
print(sdpRelaxation.primal, sdpRelaxation.status)
```
What is the exact value of violation that you expect?

**Comment by sashasami03** [comment]
The maximum value for GYNI is 1/3 for quantum , so as you said we are checking from outside I expected the value to be greater than 1/3 for Q_1 , Q_2 and Q_3 , with the value approaching 1/3 for higher levels.

**Comment by peterwittek** [comment]
At level 3 and 4, it gives 0.25 at very high precision. Are we talking about [this](http://arxiv.org/abs/1003.3844) paper? If so, this is the correct result. In the first paragraph, second column, page 3, they say that Eq(10) is saturated when all probabilities in it are 1/3, which gives you a violation of 0.25. It is the guessing probability that comes to 1/3, not the violation. Correct me if I am wrong.

**Comment by sashasami03** [comment]
yeah sorry 1/3 is for no signalling . You are correct. My mistake.

**Comment by peterwittek** [comment]
Okay, thanks. Then I close this.

**Comment by sashasami03** [comment]
You were correct writing objective functions in terms of operators can lead to mistakes, I found my mistake for GYNI now the previous code also gives the same result.
I tried writing the objective function for 3 other inequalities Mermin_1 , Mermin_2 and Svetlichny in terms of probabilities. They still give the same results I got before. For Mermin_1 maximum quantum limit is 1 but code returns 7/8 ( classical limit ), for Mermin_2 maximum quantum limit is 0.85 but the code gives 3/4 ( again classical limit ). However the code gives correct result for Svetlichny which is 0.85.

The games ( sum over respective probabilities p(a,b,c|u,v,w) )
Mermin_1   game        a xor b xor c =  u.v.w
Mermin_2  game        a xor b xor c  = u.v xor v.w 
Svetlichny game        a xor b xor c = u.v xor v.w xor w.u

The code for comparing result for these 3 games with expected results : https://gist.github.com/sashasami03/fb4ddee85e8b35c7d2a3

I even tried the method of listing all the projection operators that too gave the same result, the code for Mermin_2 by listing all projection operators : https://gist.github.com/anubhav70747/c42dd076ee9d984acbb6

**Comment by peterwittek** [comment]
While I am studying the code, could you also send me the references to the manuscripts?

**Comment by sashasami03** [comment]
http://arxiv.org/abs/1101.2477 I referred  this paper for tripartite games.

**Comment by peterwittek** [comment]
I think the boolean operations you use are slightly off. [This one](https://gist.github.com/anubhav70747/c42dd076ee9d984acbb6) uses XOR instead of or, and the comparison for the three games does modulo operations, which may not correspond to what you want. With the changes made to your gist, I get 0.875 for Mermin 2 at level 2 and 3, which is still not what we want, but better. Mermin 1 is the same.

The paper tinkers a lot with the notation. Are you sure the that the objective function is correct? There is a lot of back and forth going on with the expectation values and probabilities, which I always find confusing.

**Comment by sashasami03** [comment]
http://arxiv.org/abs/1107.2908 This paper ( equations (5) to (7) ) gives the same 3 games in terms of game. Mermin_1 equation (5) is mentioned to be 1/8 ( sum over probabilities where a xor b xor c = u.v.w ) . The change in my gist (u&v) | (v &w) gives 1 for u=v=w=1 wheres as (u&v) ^ ( v&w ) is 0 for that. In first code I used modulo 2 which is same as xor in the second code mermin2.py.

**Comment by sashasami03** [comment]
http://arxiv.org/abs/1107.2908 This paper ( equations (5) to (7) ) gives the same 3 games in terms of xor . Mermin_1 equation (7) is mentioned to be 1/8 ( sum over probabilities where a xor b xor c = u.v.w ) . The change in my gist (u&v) | (v &w) gives 1 for u=v=w=1 wheres as (u&v) ^ ( v&w ) is 0 for that. In first code I used modulo 2 which is same as xor in the second code mermin2.py.

**Comment by peterwittek** [comment]
Okay, it was a shot in the dark. I can take a look at this paper tomorrow. Till then, you can analyze the values of individual probabilities in the solution with this function:

```python
from ncpol2sdpa import get_xmat_value
a, b, c, x, y, z = 0, 0, 0, 0, 0, 0
print(P([a,b,c],[x,y,z]), get_xmat_value(P([a,b,c],[x,y,z]), sdpRelaxation))
```
Perhaps you spot where it goes wrong.

**Comment by peterwittek** [comment]
I went back to the basics and checked the maximum violation of the Mermin inequality as given in (13) in arXiv:1101.2477. It should be 4. I tried this code:

```python
from __future__ import print_function
from ncpol2sdpa import SdpRelaxation, solve_sdp, Probability

def expectation_value(P, input_):
    vals = [-1, 1]
    return sum(a*b*c*P([a, b, c], input_) for a in vals for b in vals for c in vals)

P = Probability([2, 2], [2, 2], [2, 2])
Mermin = expectation_value(P, [1, 0, 0]) + expectation_value(P, [0, 1, 0]) + \
         expectation_value(P, [0, 0, 1]) - expectation_value(P, [1, 1, 1])

sdpRelaxation = SdpRelaxation(P.get_all_operators(), verbose=0)
sdpRelaxation.get_relaxation(2, substitutions = P.substitutions)
sdpRelaxation.set_objective(-Mermin)
solve_sdp(sdpRelaxation, solver="cvxopt")
print(sdpRelaxation.primal, sdpRelaxation.status)
```
It gives `-3.99999999988 optimal`, which looks perfect to me. Now I try to see your problem.

**Comment by peterwittek** [comment]
I spotted a very slight error: Mermin 2 is (u*v)+(v*w), whereas it should be (u*v)+(u*w). It makes no difference, though. I rewrote the function definitions with lambdas to avoid possible bugs in SymPy, but I get the same result as you before. You will find the update in a comment on your gist. Higher level relaxations and other solvers do not change much.

**Comment by sashasami03** [comment]
I am really sorry for giving you the trouble, I read through the paper properly, the Mermin facet inequality ( sums over subset of probability terms occurring in Mermin xor game, thus easier to violate it ) is violated upto maximum of 4 by both quantum and no signalling which is returned correctly by SDP. Whereas the Mermin xor games  are more difficult to win and quantum is no better than classical for them which is what is returned by the SDP.

 Thank you for all the help.

**Comment by peterwittek** [comment]
No worries at all, I learned new things from this.
